launcher_base_server/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, re_path, include
from launcher_base_server.api.launcher.urls import urlpatterns as launcher_api_url_patterns
from launcher_base_server.api.site.urls import urlpatterns as site_api_url_patterns
from launcher_base_server.api.sessionserver.urls import urlpatterns as sessionserver_api_url_patterns
from launcher_base_server.api.api.urls import urlpatterns as api_api_url_patterns
from launcher_base_server.views import get_meta_info, login_view, logout_view, register_view, index_view,\
    profile_view, upload_skin, upload_cloak, download_launcher_view

urlpatterns = [
    path('', index_view),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
    path('profile/', profile_view),
    path('mineapi/', get_meta_info),
    path('download-launcher/', download_launcher_view),
    path('upload-skin/', upload_skin),
    path('upload-cloak/', upload_cloak),
    path('admin/', admin.site.urls),
    re_path(r'^mineapi/launcher/', include(launcher_api_url_patterns)),
    re_path(r'^mineapi/site/', include(site_api_url_patterns)),
    re_path(r'^mineapi/sessionserver/', include(sessionserver_api_url_patterns)),
    re_path(r'^mineapi/api/', include(api_api_url_patterns)),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

launcher_base_server/models.py
import hashlib
import random
import string

import uuid
from django.conf import settings
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.hashers import make_password
from django.db import models
from django.apps import apps
from django.core.mail import send_mail
from django.utils import timezone

from launcher_base_server.utils import construct_offline_player_uuid

# INCOMING = "money_incoming"
# SPENDING = "money_spending"
#
# TRANSACTION_TYPES = (
#     (INCOMING, "Пополнение"),
#     (SPENDING, "Расход"),
# )


class CustomUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, nickname, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not nickname:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        GlobalUserModel = apps.get_model(
            self.model._meta.app_label, self.model._meta.object_name
        )
        username = GlobalUserModel.normalize_username(nickname)
        user = self.model(nickname=username, email=email, **extra_fields)
        user.password = make_password(password)
        if settings.USE_EMAIL_VALIDATION:
            user.is_active = False
            validation_code = "".join(random.sample(string.digits + string.ascii_letters, 8))
            user.email_validation_code = validation_code
            send_mail(
                'Launcher registration validation',
                f'Hi! Your registration code is {validation_code}',
                settings.EMAIL_HOST_USER,
                [email],
                fail_silently=False,
            )

        user.save(using=self._db)
        return user

    def create_user(self, nickname, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(nickname, email, password, **extra_fields)

    def create_superuser(self, nickname, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(nickname, email, password, **extra_fields)


class User(AbstractBaseUser):
    username = None
    nickname = models.CharField(max_length=255, verbose_name="Имя пользователя", unique=True)
    email = models.EmailField('Email', unique=True)

    skin = models.ImageField(verbose_name="Скин", null=True, blank=True,
                             upload_to='skins/')

    cloak = models.ImageField(verbose_name="Плащ", null=True, blank=True,
                              upload_to='cloaks/')

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    uuid = models.UUIDField(default=uuid.uuid4, null=False, blank=False, verbose_name="UUID", unique=True)
    email_validation_code = models.CharField(max_length=6, null=True, blank=True)

    created_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True, null=False, blank=False)
    last_game_enter = models.DateTimeField(verbose_name="Дата последнего входа в игру", null=True, blank=True)

    @property
    def offline_hash(self):
        return construct_offline_player_uuid(self.nickname)

    @property
    def balance(self):
        balance = 0
        for transaction in self.transactions.all():
            balance += transaction.amount
        return balance

    USERNAME_FIELD = 'nickname'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'


class Client(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название клиента")
    client_zip = models.FileField(verbose_name="Zip файл", null=True, blank=True, upload_to='clients/',
                                  help_text="Zip файл с клиентом (Внутри должна лежать директория, которая копирует"
                                            " название клинта но с точкой веперди, например: если название клиента"
                                            " HI-TECH, то в архиве лежит папка .HI-TECH)")
    zip_hash = models.CharField(max_length=255, verbose_name="Хэш конкретной версии", null=True, blank=True)

    def __str__(self):
        return self.name

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)
        with open(f"{self.client_zip.path}", 'rb') as f:
            self.zip_hash = hashlib.sha256(f.read()).hexdigest()
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class OpenedSession(models.Model):
    server_id = models.CharField(max_length=255, null=False, blank=False)
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name="sessions", null=False, blank=False)
    create_datetime = models.DateTimeField(null=False, blank=False, default=timezone.now())


class Post(models.Model):
    image = models.ImageField(verbose_name="Изображение", null=True, blank=True,
                              upload_to='post_images/')
    header = models.CharField(max_length=255, null=False, blank=False, verbose_name="Заголовок статьи")
    text = models.TextField(null=False, blank=False, verbose_name="Текст статьи")
    created_at = models.DateTimeField(verbose_name="Дата создания", auto_now_add=True)
    created_by = models.ForeignKey("User", on_delete=models.SET_NULL, related_name="posts", null=True, blank=False,
                                   verbose_name="Создавший пользователь")

    def __str__(self):
        return self.header if len(self.header) < 100 else self.header[0: 97] + "..."

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Server(models.Model):
    name = models.CharField(max_length=255, null=False, blank=False, verbose_name="Имя сервера")
    host = models.CharField(max_length=255, null=False, blank=False, verbose_name="Хост сервера",
                            help_text="Например: 95.79.50.50 или play.madness-project.ru")
    port = models.IntegerField(null=False, blank=False, verbose_name="Порт сервера")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Сервер'
        verbose_name_plural = 'Серверы'


class Transaction(models.Model):
    user = models.ForeignKey("User", on_delete=models.CASCADE, related_name='transactions', null=False, blank=False,
                             verbose_name="Пользователь")
    amount = models.FloatField(null=False, blank=False, verbose_name="Операция")

    def __str__(self):
        return f"{self.user.nickname} {self.amount}"

    class Meta:
        verbose_name = 'Транзакция'
        verbose_name_plural = 'Транзакции'


class Launcher(models.Model):
    launcher_file = models.FileField(verbose_name="Zip или exe файл", null=True, blank=True, upload_to='launchers/')
    launcher_file_hash = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(null=False, blank=False, auto_now_add=True)

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)
        with open(f"{self.launcher_file.path}", 'rb') as f:
            self.launcher_file_hash = hashlib.sha256(f.read()).hexdigest()
        super().save(force_insert=False, force_update=False, using=None, update_fields=None)

    def __str__(self):
        return f"{self.created_at}"

    class Meta:
        verbose_name = 'Лаунчер'
        verbose_name_plural = 'Лаунчеры'

templates/minesite/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'minesite/css/style.css' %}">
    {% block extrahead %}
    {% endblock %}
</head>
<body>
<img src="{% static 'minesite/img/wallpaperflare.com_wallpaper.jpg' %}" alt="background" class="background">
<div class="header">
    {% block header %}
    {% endblock %}
</div>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/minesite/download_client.html
{% extends 'minesite/base.html' %}
{% load static %}

{% block header %}
    {% include "minesite/header.html" %}
{% endblock %}

{% block content %}
    <div class="content-container download-launcher-content-container" style="margin-top: 95px">
        <div class="download-panel">
            <p class="text-h1">Скачать</p>
            <p class="text-h2" style="margin-top: 93px;">Чтобы играть на нашем проекте вам потребуется лаунчер</p>
            <p class="text-h2">Вы можете скачать его здесь</p>
            <div class="download-block" onclick="window.location.href='{{ download_launcher_link }}'" style="margin-top: 36px">
                <img alt="downloadImage" src="{% static 'minesite/img/minecraft_logo_icon_168974 1.svg' %}">
                <p class="text-default">Загрузить клиент</p>
            </div>
        </div>
    </div>
{% endblock %}

templates/minesite/header.html
{% load static %}
<div class="header-background"></div>
<div class="header-foreground">
        <div class="left-side">
            <p class="logo-text" onclick="window.location.href='/'">MadnessLauncher</p>
        </div>
        <div class="right-side">
            <div class="nav">

                <div class="nav-item" style="margin-right: 59px"><a href="/">Главная</a></div>
                <div class="nav-item" style="margin-right: 59px"><a href="/">Магазин</a></div>
                <div class="nav-item"><a href="/">Форум</a></div>
            </div>
            <div class="user">
                {% if user.is_anonymous %}
                    <a href="/login" style="margin-right: 17px">Вход</a>
                {% else %}
                    <a href="/profile" style="margin-right: 17px">{{ user.nickname }}</a>
                    <div class="profile-head" style="background: url({% if user.skin == None or user.skin == ''%}{% static 'minesite/img/default_skin.png' %}{% else %}{{ user.skin.url }}{% endif %}) no-repeat; background-size: 360px 360px; background-position: -43px -40px;">
                {% endif %}
            </div>
        </div>
</div>

templates/minesite/index.html
{% extends 'minesite/base.html' %}

{% block header %}
    {% include "minesite/header.html" %}
{% endblock %}

{% block content %}
    <div class="content-container index-content-container" style="margin-top: 95px">
        <div class="servers-panel">
            <p class="text-h1">Серверы</p>
            <div class="servers-container">
                {% for server in servers %}
                <div class="server-item">
                    {% if server.online %}
                    <div class="left-side"><div class="online-circle"></div></div>
                    {% else %}
                    <div class="left-side"><div class="offline-circle"></div></div>
                    {% endif %}
                    <div class="right-side">
                        <div class="up-row">
                            <p>{{ server.name }}</p><p>{{ server.players_now }}/{{ server.players_max }}</p>
                        </div>
                        <div class="down-row">
                            <p>{{ server.host }}:{{ server.port }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="submit-button" type="button" onclick="window.location.href='/download-launcher'" style="margin-top: 47px">ИГРАТЬ</button>
        </div>
        <div class="news-panel">
            <p class="text-h1">Новости</p>
            <div class="ads-container">
                {% for post in posts %}
                <div class="ad-container">
                    {% if post.image %}
                    <div class="ad-image-container">
                        <img class="ad-image" alt="ad_image" src="{{ post.image }}">
                    </div>
                    {% endif %}
                    <p class="text-h2">{{ post.header }}</p>
                    <p class="text-default">{{ post.text }}</p>
                    <div class="ad-underline">
                        <p class="text-hint">создано {{ post.created_at }} пользователем {{ post.creator }}</p>
                        <div class="underline"></div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/minesite/login.html
{% extends 'minesite/base.html' %}

{% block content %}
    <div class="login-container">
        <form action="/login/" method="post" class="login-background">{% csrf_token %}
            <p class="text-h1"  style="margin-top: 21px">ВОЙТИ</p>
            <div class="input-field" style="margin-top: 26px">
                <p>Никнейм</p>
                <input type="text" name="nickname" id="nickname" class="input-field-input">
            </div>
            <div class="input-field" style="margin-top: 26px">
                <p>Пароль</p>
                <input type="password" name="password" id="password" class="input-field-input">
            </div>
            <button class="submit-button" value="OK" type="submit" style="margin-top: 26px">ВХОД</button>
            <a href="/register" style="margin-top: 12px">Регистрация</a>
        </form>
    </div>
{% endblock %}

templates/minesite/profile.html
{% extends 'minesite/base.html' %}
{% load static %}

{% block extrahead %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/94/three.min.js" integrity="sha256-NGC9JEuTWN4GhTj091wctgjzftr+8WNDmw0H8J5YPYE=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/gh/InventivetalentDev/MineRender@1.4.6/dist/skin.min.js"></script>
{% endblock %}

{% block header %}
    {% include "minesite/header.html" %}
{% endblock %}

{% block content %}
    <div class="content-container profile-content-container" style="margin-top: 95px">
        <div class="profile-panel">
            <p class="text-h1">Профиль</p>
            <div class="profile-data-container">
                <div class="skin-data-container">
                    <div class="skin-container" id="skin-container">

                    </div>
                    <script>
                        let cur_options = {
                            showOutlines: false,    // Debugging - Show bounding boxes
                            showAxes: false,        // Debugging - Show the scene's axes
                            showGrid: false,        // Debugging - Show coordinate grid
                            autoResize: false,      // Whether to automatically resize the canvas
                            controls: {
                                enabled: true,      // Toggle controls
                                zoom: false,         // Toggle zooming
                                rotate: true,      // Toggle rotation
                                pan: false           // Toggle panning
                            },
                            camera: {               // Camera position
                                x: 20,
                                y: 30,
                                z: 30,
                                target: [0, 20, 0]   // Where the camera should look
                            },
                            canvas: {               // Dimensions the canvas starts off with (undefined -> use window size)
                                width: document.getElementById("skin-container").offsetWidth,
                                height: document.getElementById("skin-container").offsetHeight
                            },
                            pauseHidden: true       // Whether to pause animations that aren't currently visible
                        };
                        let skinRender = new SkinRender(cur_options, document.getElementById("skin-container"));
                        let loc = window.location.origin
                        let cur_url = loc + "{% if user.skin == None or user.skin == ''%}{% static 'minesite/img/default_skin.png' %}{% else %}{{ user.skin.url }}{% endif %}"
                        let cur_cape_url = loc + "{% if user.cloak  == None or user.cloak == '' %}''{% else %}{{user.cloak.url}}{% endif %}"
                        console.log(cur_url)
                        console.log(cur_cape_url)
                        {% if user.cloak == None or user.cloak == ''  %}
                            skinRender.render(cur_url)
                            console.log(111111111111111)
                        {% else %}
                        skinRender.render({
                            "url": cur_url,
                            "capeUrl": cur_cape_url
                        });
                        console.log(22222222222222222)
                        {% endif %}
                    </script>
                    <p class="text-default">Установить</p>
                    <div class="install-buttons">
                        <form action="/upload-skin/" method="post" enctype="multipart/form-data">{% csrf_token %}
                            <input type="file" name="skin" accept="image/png" id="id_skin" onchange="form.submit()" style="display: none">
                            <label for="id_skin"><div class="submit-button" style="display: flex;justify-content: center;align-items: center;">СКИН</div></label>
                        </form>
                        <form action="/upload-cloak/" method="post" enctype="multipart/form-data">{% csrf_token %}
                            <input type="file" name="cloak" accept="image/png" id="id_cloak" onchange="form.submit()" style="display: none">
                            <label for="id_cloak"><div class="submit-button" style="display: flex;justify-content: center;align-items: center; margin-left: 10px">ПЛАЩ</div></label>
                        </form>
                    </div>
                </div>
                <div class="profile-info">
                    <p class="text-default">Ник: {{ user.nickname }}</p>
                    <p class="text-default">Баланс: {{ user.balance }}</p>
                    <p class="text-default">Дата регистрации: {{ user.created_at }}</p>
                    <p class="text-default">Дата последнего входа: {{ user.last_login }}</p>
                    <p class="text-default">Дата последнего входа в игру: {{ user.last_game_enter|default_if_none:"Не было" }}</p>
                    <div class="profile-actions-buttons">
                        <button class="submit-button" type="button">ПОПОЛНИТЬ БАЛАНС</button>
                        <form action="/logout/" method="post"> {% csrf_token %}
                        <button class="bad-button" type="submit" style="margin-top: 15px">ВЫХОД</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/minesite/register.html
{% extends 'minesite/base.html' %}

{% block content %}
    <div class="register-container">
        <form autocomplete="off" action="/register/" method="post" class="register-background">{% csrf_token %}
            <p class="text-h1"  style="margin-top: 21px">РЕГИСТРАЦИЯ</p>
            <div class="register-inputs-grid" style="margin-top: 28px">
                <div class="register-inputs-grid-column">
                    <div class="input-field">
                        <p>Никнейм</p>
                        <input autocomplete="off" type="text" name="nickname" id="nickname" class="input-field-input">
                    </div>
                    <div class="input-field" style="margin-top: 26px">
                        <p>Пароль</p>
                        <input autocomplete="new-password" type="password" name="password" id="password" class="input-field-input">
                    </div>
                </div>
                <div class="register-inputs-grid-column" style="margin-left: 47px">
                    <div class="input-field">
                        <p>E-mail</p>
                        <input autocomplete="off" type="text" name="email" id="email" class="input-field-input">
                    </div>
                    <div class="input-field" style="margin-top: 26px">
                        <p>Подтвердите пароль</p>
                        <input autocomplete="new-password" type="password" name="password_repeat" id="password_repeat" class="input-field-input">
                    </div>
                </div>
            </div>
            <button class="submit-button" value="OK" type="submit" style="margin-top: 26px">ЗАРЕГИСТРИРОВАТЬСЯ</button>
            <a href="/login" style="margin-top: 12px">Вход</a>
        </form>
    </div>
{% endblock %}